xf86-video-ati: Upgrade to version 7.6.1
Fixes build errors such as:
     <build_dir>/tmp/work/dbft3b-poky-linux/xf86-video-ati/2_7.4.0+gitAUTOINC+906a0ec922-r21.1/git/src/drmmode_display.c:795:2:
     error: too few arguments to function 'PixmapStartDirtyTracking'
       PixmapStartDirtyTracking(ppix, screenpix, 0, 0);

Signed-off-by: Drew Moseley <drew_moseley@mentor.com>